all: q1 q2 q3 q4 q5 q6

q1: psq11.1.c
		gcc -o psq11.1 psq11.1.c -lpthread

q2: psq11.2.c
		gcc -o psq11.2 psq11.2.c -lpthread

q3: psq11.3.c
		gcc -o psq11.3 psq11.3.c -lpthread

q4: psq11.4.c
		gcc -o psq11.4 psq11.4.c -lpthread

q5: psq11.5.c
		gcc -o psq11.5 psq11.5.c -lpthread

q6: psq11.6.c 
		gcc -o psq11.6 psq11.6.c -lpthread

clean: 
		rm -f q1 *.o
		rm -f q2 *.o
		rm -f q3 *.o
		rm -f q4 *.o
		rm -f q5 *.o
		rm -f q6 *.o

